name: axolon_inventory_manager
description: "Axolon Inventory App"
publish_to: 'none' 

version: 4.05.050+44


environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^0.13.6
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  shimmer: ^3.0.0
  getwidget: ^4.0.0
  dropdown_button2: ^2.3.9
  encrypt: ^5.0.3
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1
  auto_size_text: ^3.0.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.4
  scan: ^1.6.0
  permission_handler: ^11.1.0
  gallery_saver: ^2.3.2
  path_provider: ^2.1.2
  barcode: ^2.2.3
  barcode_widget: ^2.0.3

  flutter_svg: ^1.1.3
  dotted_border: ^2.1.0
  open_filex: ^4.3.4
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  flutter_image_compress: ^2.1.0
  # pdf: ^3.10.6
  printing: ^5.11.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename_app: ^1.3.1
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#3457a7"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/drawer/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
